### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by zdolny** [sbojdo/array-names#1]
1. Dodaj doctype
2. Poniewaz uzyles splice zamiast push, Twoj kod jest mniej reuzywalny. Push dodaje element do tablicy niezaleznie ile ma ona elementow, w splice musisz dokladnie okreslic gdzie chcesz dodac nowy element, czyli musisz wiedziec ile tablica ma elementow. Proponuje zamiast sztywno wpisywac, zeby przed 8 indeksem wpadal nowy element, napisac, ze przed ostatnim elementem ma sie dodac nowy.

**Comment by sbojdo** [comment]
Przerobiłem to na Pusha bo rzeczywiście ma większy sens i mniej kodu wychodzi, zmiany w branchu jsPushAdded
